### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by falematte** [bfontaine/clj#2]
What is the state of this project? I think this would be really useful for my workflow!

**Comment by bfontaine** [comment]
I’m not actively using it right now, but I’m happy to maintain it 🙂

**Comment by falematte** [comment]
Why? Do you think it is usable or some fundamental pieces are missing? Thank you for the answer

**Comment by bfontaine** [comment]
I’m writing Clojure/ClojureScript all day at work and don’t use as much Python as I used to.

The code is stable; I might add a couple more functions but the core ones are already there.

**Comment by falematte** [comment]
Thank you for the detailed answer! Have fun with clojure!

**Comment by bfontaine** [comment]
Thank you 😊
